exclude:
  - vendor
  - "*.Rmd"
baseurl: /ESM296-3W-2016
gems: # https://pages.github.com/versions/
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji
#  - jekyll-last-modified-at

# Conversion
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
